analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.config.dart
  errors:
    prefer_single_quotes: ignore
    prefer_const_constructors: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
  - unnecessary_const


dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 100
    number-of-parameters: 5
    maximum-nesting-level: 5
    prefer-correct-identifier-length:
      max-identifier-length: 30
      min-identifier-length: 4
    prefer-trailing-coma:
    break-on: 1
  metrics-exclude:
    - test/**
  rules:
    - prefer-const-border-radius
    - avoid-unnecessary-type-assertions
    - double-literal-format
    - no-equal-arguments
    - prefer-match-file-name